auto_interpolation_2d – GVTD-HeCs
auto_interpolation_2d Subroutine
65 statements
Source File
public subroutine auto_interpolation_2d(x, y, r, q, u, v, undef, stdopt)
Automatic interpolation for 2d data (continuous running of interpolation_2d)
Arguments
Type Intent Optional Attributes Name
double precision, intent(in) :: x(:)
reference grid 1
double precision, intent(in) :: y(:)
reference grid 2
double precision, intent(in) :: r(:)
target grid 1
double precision, intent(in) :: q(:)
target grid 2
double precision, intent(in) :: u(size(x),size(y))
reference data
double precision, intent(inout) :: v(size(r),size(q))
interpolated data
double precision, intent(in), optional :: undef
undefined value
logical, intent(in), optional :: stdopt
Display debug messages. (default: .false. == No display)
Calls
Contents
Call graph
auto_interpolation_2d calls auto_interpo_search_2d, interpolation_2d, interpolation_1d
auto_interpo_search_2d calls auto_interpo_search_1d
interpolation_2d calls interpolation_1d