cart_conv_scal – GVTD-X
cart_conv_scal Subroutine
94 statements
Source File
public subroutine cart_conv_scal(r, theta, v, x, y, xc, yc, u, undef, undefg, stdopt)
Convert polar grid with the origin of the storm center to the Cartesian grid (from STPK) The procedure: (1) Define the given Cartesian grid (x-y) on the polar grid (2) Search the 4 nearest points on the polar grid for each Cartesian grid point (3) Performing the bilinear interpolation of the 4 values defined on the polar grid to the Cartesian grid.
Arguments
Type Intent Optional Attributes Name
double precision, intent(in) :: r(:)
R-coordinate on the polar grid with the origin (xc, yc).
double precision, intent(in) :: theta(:)
theta-coordinate of the polar grid with the origin (xc, yc) [rad]
double precision, intent(in) :: v(size(r),size(theta))
Values defined on the polar grid
double precision, intent(in) :: x(:)
X-coordinate on the Cartesian grid
double precision, intent(in) :: y(:)
Y-coordinate on the Cartesian grid
double precision, intent(in) :: xc
X-component of the storm center
double precision, intent(in) :: yc
Y-component of the storm center
double precision, intent(out) :: u(size(x),size(y))
Values converted to the Cartesian grid
double precision, intent(in), optional :: undef
Missing value for the outside of the Cartesian grid area (default: -999.0)
double precision, intent(in), optional :: undefg
Missing value for the inside of the Cartesian grid area (default: -999.0)
logical, intent(in), optional :: stdopt
Display debug messages. (default: .false. == No display)
Calls
Contents
None
Call graph
cart_conv_scal calls xy_2_rt, interpo_search_2d, undef_checker_2d, interpolation_2d
xy_2_rt calls datan
interpo_search_2d calls interpo_search_1d
undef_checker_2d calls undef_checker_1d
interpolation_2d calls interpolation_1d