fp_gauss – GVTD-HeCs
fp_gauss Subroutine
76 statements
Source File
public subroutine fp_gauss(c, d, x)
Gauss-Jordan method with fully pivotting (from STPK)
Arguments
Type Intent Optional Attributes Name
double precision, intent(in) :: c(size(d),size(d))
Square matrix (array is the first elements)
double precision, intent(in) :: d(:)
Vector
double precision, intent(inout) :: x(size(d))
Vector for unknown variables
Called by
Contents
None
Call graph
fp_invert_mat calls fp_gauss
retrieve_velocity_gbvtd calls fp_gauss
retrieve_velocity2_gvtdx calls fp_gauss
retrieve_velocity_gvtd calls fp_gauss
retrieve_velocity_gvtdx calls fp_gauss