interpolation_1d – GVTD-HeCs
interpolation_1d Subroutine
19 statements
Source File
public subroutine interpolation_1d(x, y, point, val)
Perform linear interpolation to the "point" on the Cartesian (x) grid (from STPK)
Arguments
Type Intent Optional Attributes Name
double precision, intent(in) :: x(2)
The nearest west and east points for "point"
double precision, intent(in) :: y(2)
Values defined at x. y(1) at x(1) y(2) at x(2)
double precision, intent(in) :: point
The target point for the interpolation
double precision, intent(out) :: val
Interpolated value
Called by
Contents
None
Call graph
interpolation_2d calls interpolation_1d
auto_interpolation_2d calls interpolation_1d, interpolation_2d
tangent_conv_scal calls interpolation_2d
cart_conv_scal calls interpolation_2d