interpo_search_2d – GVTD-HeCs
interpo_search_2d Subroutine
26 statements
Source File
public subroutine interpo_search_2d(x, y, pointx, pointy, i, j, undeff, stdopt)
Floor function for the real grid points (from STPK)
Arguments
Type Intent Optional Attributes Name
double precision, intent(in) :: x(:)
X-coordinate
double precision, intent(in) :: y(:)
Y-coordinate
double precision, intent(in) :: pointx
The X point in real
double precision, intent(in) :: pointy
The Y point in real
integer, intent(out) :: i
floor(pointx)
integer, intent(out) :: j
floor(pointy)
integer, intent(in), optional :: undeff
In case of (x(1)>pointx or y(1)>pointy), the value returned to i and j (default = 0)
logical, intent(in), optional :: stdopt
Display debug messages (default = .false. = Not display)
Calls
Called by
Contents
Call graph
interpo_search_2d calls interpo_search_1d
tangent_conv_scal calls interpo_search_2d
cart_conv_scal calls interpo_search_2d