ll2rt – GVTD-HeCs
ll2rt Subroutine
42 statements
Source File
public subroutine ll2rt(lon0, lat0, lon1, lat1, r, theta)
calculate radial and azimuthal location at (lon1,lat1) on the polar coordinate with the center of (lon0,lat0)
Arguments
Type Intent Optional Attributes Name
double precision, intent(in) :: lon0
the center longitude (rad)
double precision, intent(in) :: lat0
the center latitude (rad)
double precision, intent(in) :: lon1
target longitude (rad)
double precision, intent(in) :: lat1
target latitude (rad)
double precision, intent(inout) :: r
radial distance (m)
double precision, intent(inout) :: theta
azimuthal angle (rad)
Calls
Contents
Call graph
ll2rt calls ll2radi, dcos, dsin, datan
ll2radi calls dcos, dsin, dacos