prod_vortex_structure – GVTD-HeCs
prod_vortex_structure Subroutine
235 statements
Source File
public subroutine prod_vortex_structure(r, t, rmax, vmax, c1u, c2u, Vt, Vr, Vt_pert, Vr_pert, Vt_pert_ang, Vr_pert_ang, ropt, dopt, Vt_0, Vr_0, Uxm, Vym, flag_disp)
Producing vortex structure with rmax, vmax, and umax
Arguments
Type Intent Optional Attributes Name
double precision, intent(in) :: r(:)
radius [m]
double precision, intent(in) :: t(:)
azimuthal angle [rad]
double precision, intent(in) :: rmax
radius of maximum tangential wind speed [m]
double precision, intent(in) :: vmax
maximum tangential wind speed [m s-1]
double precision, intent(in) :: c1u
coefficient 1 for radial wind [s-1]
double precision, intent(in) :: c2u
coefficient 2 for radial wind [s-1]
double precision, intent(out) :: Vt(size(r),size(t))
Profile of tangential wind
double precision, intent(out) :: Vr(size(r),size(t))
Profile of radial wind
double precision, intent(in), optional :: Vt_pert(:)
perturbations of tangential wind [m s-1]
double precision, intent(in), optional :: Vr_pert(:)
perturbations of radial wind [m s-1]
double precision, intent(in), optional :: Vt_pert_ang(:)
angles of tangential wind [rad]
double precision, intent(in), optional :: Vr_pert_ang(:)
angles of radial wind [rad]
logical, intent(in), optional :: ropt
option for radial variation of perturbation Vt and Vr
logical, intent(in), optional :: dopt
option for divergent components of perturbation Vt and Vr
double precision, intent(out), optional :: Vt_0(:)
Radial profile of axisymmetric Vt [m s-1]
double precision, intent(out), optional :: Vr_0(:)
Radial profile of axisymmetric Vr [m s-1]
double precision, intent(out), optional :: Uxm(2)
Azimuthal averaged X-wind of wavenumber-1 component [m s-1]
double precision, intent(out), optional :: Vym(2)
Azimuthal averaged Y-wind of wavenumber-1 component [m s-1]
logical, intent(in), optional :: flag_disp
Calls
Contents
Call graph
prod_vortex_structure calls green_func, dcos, line_integral, dsin
green_func calls stdout