Retrieve_velocity_GVTDX – GVTD-HeCs
Retrieve_velocity_GVTDX Subroutine
231 statements
Source File
public subroutine Retrieve_velocity_GVTDX(nrot, ndiv, r, t, rh, td, rdiv, Vd, Vn, RadTC, VT, VR, VRT0, VDR0, VRTn, VRRn, VDTm, VDRm, undef, phin, zetan, VRT0_GVTD, VDR0_GVTD, VRTns, VRTnc, VRRns, VRRnc, Vn_0)
Solve unknown variables and return wind velocity on R-T coordinates.
-------------------------------------------------------
-- [relationship between r and rh] --
-------------------------------------------------------
-- i-1 i i+1
-- ...|-- --|-- --|... : r(1:size(r)) = velocity radii
-- |-- --|-- --|-- --| : rh(1,size(r)+1) = potential radii
--i-1 i i+1 i+2
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nrot
wave number for rotating wind
integer, intent(in) :: ndiv
wave number for divergent wind
double precision, intent(in) :: r(:)
radial coordinate on which Vd is defined [m]
double precision, intent(in) :: t(:)
azimuthal coordinate on which Vd is defined [rad]
double precision, intent(in) :: rh(size(r)+1)
radial coordinate on which Phi (staggered for Vd) is defined [m]
double precision, intent(in) :: td(size(r),size(t))
radar azimuthal angle defined at Vd(r,t) [rad]
double precision, intent(in) :: rdiv(:)
radial coordinate on which Dc (staggered for Vd) is defined [m]
double precision, intent(inout) :: Vd(size(r),size(t))
Doppler velocity defined on r-t [m s-1]
double precision, intent(in) :: Vn
y component of storm-relative mean wind on Cartesian coordinate (x,y) which is defined in the direction of the radar to TC ccenter [m s-1]
double precision, intent(in) :: RadTC
Distance from radar to TC center [m]
double precision, intent(out) :: VT(size(r),size(t))
retrieved total tangential wind [m s-1]
double precision, intent(out) :: VR(size(r),size(t))
retrieved total radial wind [m s-1]
double precision, intent(out) :: VRT0(size(r),size(t))
retrieved axisymmetric radial component of rotating wind [m s-1]
double precision, intent(out) :: VDR0(size(r),size(t))
retrieved axisymmetric tangential component of divergent wind [m s-1]
double precision, intent(out) :: VRTn(nrot,size(r),size(t))
retrieved tangential component of rotating wind [m s-1]
double precision, intent(out) :: VRRn(nrot,size(r),size(t))
retrieved radial component of rotating wind [m s-1]
double precision, intent(out) :: VDTm(ndiv,size(r),size(t))
retrieved tangential component of divergent wind [m s-1]
double precision, intent(out) :: VDRm(ndiv,size(r),size(t))
retrieved radial component of divergent wind [m s-1]
double precision, intent(in), optional :: undef
undefined value for Vd
double precision, intent(out), optional :: phin(nrot,size(r),size(t))
retrieved stream function [m2 s-1]
double precision, intent(out), optional :: zetan(nrot,size(r),size(t))
retrieved vorticity [s-1]
double precision, intent(out), optional :: VRT0_GVTD(size(r),size(t))
retrieved axisymmetric radial component of pseudo-GVTD tangential wind [m s-1]
double precision, intent(out), optional :: VDR0_GVTD(size(r),size(t))
retrieved axisymmetric tangential component of pseudo-GVTD tangential wind [m s-1]
double precision, intent(out), optional :: VRTns(nrot,size(r),size(t))
Sine component of retrieved asymmetric radial wind [m s-1]
double precision, intent(out), optional :: VRTnc(nrot,size(r),size(t))
Cosine component of retrieved asymmetric radial wind [m s-1]
double precision, intent(out), optional :: VRRns(nrot,size(r),size(t))
Sine component of retrieved asymmetric tangential wind [m s-1]
double precision, intent(out), optional :: VRRnc(nrot,size(r),size(t))
Cosine component of retrieved asymmetric tangential wind [m s-1]
double precision, intent(out), optional :: Vn_0(size(r),size(t))
Aliased component to asymmetric tangential wind from (storm-relative) mean wind [m s-1]
Calls
Contents
Call graph
retrieve_velocity_gvtdx calls stdout, interpo_search_1d, dcos, fp_gauss