Retrieve_velocity_GVTD – GVTD-HeCs
Retrieve_velocity_GVTD Subroutine
108 statements
Source File
public subroutine Retrieve_velocity_GVTD(nasym, r, t, td, Vd, Un, Vn, RadTC, VT, VR, VT0, VR0, VTSn, VTCn, undef)
Solve unknown variables and return wind velocity on R-T coordinates based on the GVTD technique.
------------------------------------------------------
[relationship between r and rh] --
------------------------------------------------------
i-1 i i+1
...|-- --|-- --|... : r(1:size(r)) = velocity radii
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nasym
wave number for asymmetric tangential wind
double precision, intent(in) :: r(:)
radial coordinate on which Vd is defined [m]
double precision, intent(in) :: t(:)
azimuthal coordinate on which Vd is defined [rad]
double precision, intent(in) :: td(size(r),size(t))
radar azimuthal angle defined at Vd(r,t) [rad]
double precision, intent(inout) :: Vd(size(r),size(t))
Doppler velocity defined on r-t [m s-1]
double precision, intent(in) :: Un(2)
Parallel component to radar in environmental wind, defined on r-t [m s-1]
double precision, intent(in) :: Vn(2)
Normal component to radar in environmental wind, defined on r-t [m s-1]
double precision, intent(in) :: RadTC
Distance from radar to TC center [m]
double precision, intent(out) :: VT(size(r),size(t))
retrieved total tangential wind [m s-1]
double precision, intent(out) :: VR(size(r),size(t))
retrieved total radial wind [m s-1]
double precision, intent(out) :: VT0(size(r),size(t))
retrieved axisymmetric radial component of rotating wind [m s-1]
double precision, intent(out) :: VR0(size(r),size(t))
retrieved axisymmetric tangential component of divergent wind [m s-1]
double precision, intent(out) :: VTSn(nasym,size(r),size(t))
retrieved tangential component of rotating wind [m s-1]
double precision, intent(out) :: VTCn(nasym,size(r),size(t))
retrieved radial component of rotating wind [m s-1]
double precision, intent(in), optional :: undef
undefined value for Vd
Calls
Contents
None
Call graph
retrieve_velocity_gvtd calls stdout, dcos, fp_gauss