rt2ll – GVTD-X
rt2ll Subroutine
39 statements
Source File
public subroutine rt2ll(r, theta, lon0, lat0, lon, lat)
calculate (lon,lat) from radial and azimuthal grid (r,theta) on the polar coordinate with the origin of (lon0,lat0)
Arguments
Type Intent Optional Attributes Name
double precision, intent(in) :: r
radial distance from (lon0,lat0) (m)
double precision, intent(in) :: theta
azimuthal angle from (lon0,lat0) (rad)
double precision, intent(in) :: lon0
longitude of the center on the polar coordinate (rad)
double precision, intent(in) :: lat0
latitude of the center on the polar coordinate (rad)
double precision, intent(inout) :: lon
target longitude (rad)
double precision, intent(inout) :: lat
target latitude (rad)
Calls
Contents
None
Call graph
rt2ll calls dcos, dsin, dasin