stdout – GVTD-HeCs
stdout Subroutine
22 statements
Source File
public subroutine stdout(message, routine_name, mtype)
Standard output for message
Arguments
Type Intent Optional Attributes Name
character, intent(in) :: message
output message
character, intent(in) :: routine_name
called routine name
integer, intent(in) :: mtype
message type 0: message, -1: error, 1: warning
Called by
Contents
Call graph
retrieve_velocity_gvtd calls stdout
retrieve_velocity_gbvtd calls stdout, calc_psid
calc_psid calls stdout
read_file_3d calls stdout
green_func calls stdout
retrieve_velocity_gvtdx calls stdout
prod_vortex_structure calls green_func