tangent_conv_scal – GVTD-HeCs
tangent_conv_scal Subroutine
87 statements
Source File
public subroutine tangent_conv_scal(x, y, xc, yc, u, r, theta, v, undef, undefg, stdopt)
Convert the Cartesian grid to polar grid with the origin of the storm center (from STPK) The procedure: (1) Define the given polar grid (r-theta) on the Cartesian grid (2) Search the 4 nearest points on the Cartesian grid (x-y) for each polar grid point (3) Performing the bilinear interpolation of the 4 values defined on the Cartesian grid to the polar grid.
Arguments
Type Intent Optional Attributes Name
double precision, intent(in) :: x(:)
X-coordinate on the Cartesian grid
double precision, intent(in) :: y(:)
Y-coordinate on the Cartesian grid
double precision, intent(in) :: xc
X-component of the storm center
double precision, intent(in) :: yc
Y-component of the storm center
double precision, intent(in) :: u(size(x),size(y))
Values defined on the Cartesian grid
double precision, intent(in) :: r(:)
R-coordinate on the polar grid with the origin (xc, yc).
double precision, intent(in) :: theta(:)
theta-coordinate of the polar grid with the origin (xc, yc) [rad]
double precision, intent(out) :: v(size(r),size(theta))
Values converted to the polar grid
double precision, intent(in), optional :: undef
Missing value for the outside of the polar grid area (default: -999.0)
double precision, intent(in), optional :: undefg
Missing value for the inside of the polar grid area (default: -999.0)
logical, intent(in), optional :: stdopt
Display debug messages. (default: .false. == No display)
Calls
Contents
None
Call graph
tangent_conv_scal calls rt_2_xy, undef_checker_2d, interpo_search_2d, interpolation_2d
rt_2_xy calls dcos, dsin
undef_checker_2d calls undef_checker_1d
interpo_search_2d calls interpo_search_1d
interpolation_2d calls interpolation_1d